### PR TITLE
Resolves memory issue

### LINKED ISSUE #31: memory unsafety -- address sanitizer failure
**Describe the bug**
This looks like quite a serious bug, the test suite is failing address sanitizer:

```
Test Suite 'All tests' started at 2019-07-22 11:43:35.772 am
Test Suite 'apnswiftPackageTests.xctest' started at 2019-07-22 11:43:35.773 am
Test Suite 'APNSwiftConfigurationTests' started at 2019-07-22 11:43:35.773 am
Test Case '-[APNSwiftTests.APNSwiftConfigurationTests testProductionConfiguration]' started.
Test Case '-[APNSwiftTests.APNSwiftConfigurationTests testProductionConfiguration]' passed (0.135 seconds).
Test Case '-[APNSwiftTests.APNSwiftConfigurationTests testSandboxConfiguration]' started.
Test Case '-[APNSwiftTests.APNSwiftConfigurationTests testSandboxConfiguration]' passed (0.001 seconds).
Test Case '-[APNSwiftTests.APNSwiftConfigurationTests testSignature]' started.
=================================================================
==41340==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x615000013880 at pc 0x0001053595ee bp 0x7ffeea8c8660 sp 0x7ffeea8c7e08
READ of size 513 at 0x615000013880 thread T0
    #0 0x1053595ed in wrap_strlen (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x175ed)
    #1 0x10a9d6ed8 in mem_puts (libcrypto.1.0.0.dylib:x86_64+0xa8ed8)
    #2 0x10a9d638a in BIO_puts (libcrypto.1.0.0.dylib:x86_64+0xa838a)
    #3 0x10d402450 in closure #1 in APNSwiftSigner.sign(digest:) APNSwiftSigner.swift:39
    #4 0x10d4025f2 in thunk for @callee_guaranteed (@unowned UnsafeRawBufferPointer) -> (@unowned Int, @error @owned Error) <compiler-generated>
    #5 0x10d402693 in partial apply for thunk for @callee_guaranteed (@unowned UnsafeRawBufferPointer) -> (@unowned Int, @error @owned Error) <compiler-generated>
    #6 0x10d98c8af in ByteBuffer.withUnsafeReadableBytes<A>(_:) ByteBuffer-core.swift:530
    #7 0x10d3ffc3b in APNSwiftSigner.sign(digest:) APNSwiftSigner.swift:38
    #8 0x10d41abe3 in APNSwiftConfigurationTests.testSignature() APNSwiftConfigurationTests.swift:57
    #9 0x10d41b53d in @objc APNSwiftConfigurationTests.testSignature() <compiler-generated>
    #10 0x7fff2f2225eb in __invoking___ (CoreFoundation:x86_64h+0x4a5eb)
    #11 0x7fff2f2224a3 in -[NSInvocation invoke] (CoreFoundation:x86_64h+0x4a4a3)
    #12 0x1060f4c6d in __24-[XCTestCase invokeTest]_block_invoke_2.214 (XCTest:x86_64+0x2dc6d)
    #13 0x10618113a in -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] (XCTest:x86_64+0xba13a)
    #14 0x1060ff8da in -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] (XCTest:x86_64+0x388da)
    #15 0x1060f4bfd in __24-[XCTestCase invokeTest]_block_invoke.208 (XCTest:x86_64+0x2dbfd)
    #16 0x10616858f in -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] (XCTest:x86_64+0xa158f)
    #17 0x1061684ac in -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] (XCTest:x86_64+0xa14ac)
    #18 0x1060f46ae in __24-[XCTestCase invokeTest]_block_invoke (XCTest:x86_64+0x2d6ae)
    #19 0x1060f41a7 in -[XCTestCase testContextPerformInScope:] (XCTest:x86_64+0x2d1a7)
    #20 0x1060f4241 in -[XCTestCase invokeTest] (XCTest:x86_64+0x2d241)
    #21 0x1060f6020 in __26-[XCTestCase performTest:]_block_invoke_2 (XCTest:x86_64+0x2f020)
    #22 0x10616858f in -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] (XCTest:x86_64+0xa158f)
    #23 0x1061684ac in -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] (XCTest:x86_64+0xa14ac)
    #24 0x1060f5f37 in __26-[XCTestCase performTest:]_block_invoke.342 (XCTest:x86_64+0x2ef37)
    #25 0x10617880b in +[XCTContext runInContextForTestCase:block:] (XCTest:x86_64+0xb180b)
    #26 0x1060f56aa in -[XCTestCase performTest:] (XCTest:x86_64+0x2e6aa)
    #27 0x106147163 in -[XCTest runTest] (XCTest:x86_64+0x80163)
    #28 0x1060efd4a in __27-[XCTestSuite performTest:]_block_invoke (XCTest:x86_64+0x28d4a)
    #29 0x1060ef474 in -[XCTestSuite _performProtectedSectionForTest:testSection:] (XCTest:x86_64+0x28474)
    #30 0x1060ef771 in -[XCTestSuite performTest:] (XCTest:x86_64+0x28771)
    #31 0x106147163 in -[XCTest runTest] (XCTest:x86_64+0x80163)
    #32 0x1060efd4a in __27-[XCTestSuite performTest:]_block_invoke (XCTest:x86_64+0x28d4a)
    #33 0x1060ef474 in -[XCTestSuite _performProtectedSectionForTest:testSection:] (XCTest:x86_64+0x28474)
    #34 0x1060ef771 in -[XCTestSuite performTest:] (XCTest:x86_64+0x28771)
    #35 0x106147163 in -[XCTest runTest] (XCTest:x86_64+0x80163)
    #36 0x1060efd4a in __27-[XCTestSuite performTest:]_block_invoke (XCTest:x86_64+0x28d4a)
    #37 0x1060ef474 in -[XCTestSuite _performProtectedSectionForTest:testSection:] (XCTest:x86_64+0x28474)
    #38 0x1060ef771 in -[XCTestSuite performTest:] (XCTest:x86_64+0x28771)
    #39 0x106147163 in -[XCTest runTest] (XCTest:x86_64+0x80163)
    #40 0x106192ab5 in __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke (XCTest:x86_64+0xcbab5)
    #41 0x106192bb1 in __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.84 (XCTest:x86_64+0xcbbb1)
    #42 0x1061162e8 in -[XCTestObservationCenter _observeTestExecutionForBlock:] (XCTest:x86_64+0x4f2e8)
    #43 0x106192873 in -[XCTTestRunSession runTestsAndReturnError:] (XCTest:x86_64+0xcb873)
    #44 0x1060d2a9f in -[XCTestDriver runTestsAndReturnError:] (XCTest:x86_64+0xba9f)
    #45 0x106174b53 in _XCTestMain (XCTest:x86_64+0xadb53)
    #46 0x1053350f9 in main (xctest:x86_64+0x1000020f9)
    #47 0x7fff6693bc48 in start (libdyld.dylib:x86_64+0x11c48)

0x615000013880 is located 0 bytes to the right of 512-byte region [0x615000013680,0x615000013880)
allocated by thread T0 here:
    #0 0x1053a27d3 in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x607d3)
    #1 0x10d96fc06 in closure #1 in ByteBufferAllocator.init() ByteBuffer-core.swift:69
    #2 0x10d96fc68 in @objc closure #1 in ByteBufferAllocator.init() <compiler-generated>
    #3 0x10d975195 in static ByteBuffer._Storage.allocateAndPrepareRawMemory(bytes:allocator:) ByteBuffer-core.swift:226
    #4 0x10d977360 in static ByteBuffer._Storage.reallocated(minimumCapacity:allocator:) ByteBuffer-core.swift:266
    #5 0x10d971480 in ByteBuffer.init(allocator:startingCapacity:) ByteBuffer-core.swift:407
    #6 0x10d9709ba in ByteBufferAllocator.buffer(capacity:) ByteBuffer-core.swift:90
    #7 0x10d418aa9 in APNSwiftConfigurationTests.testSignature() APNSwiftConfigurationTests.swift:49
    #8 0x10d41b53d in @objc APNSwiftConfigurationTests.testSignature() <compiler-generated>
    #9 0x7fff2f2225eb in __invoking___ (CoreFoundation:x86_64h+0x4a5eb)
    #10 0x7fff2f2224a3 in -[NSInvocation invoke] (CoreFoundation:x86_64h+0x4a4a3)
    #11 0x1060f4c6d in __24-[XCTestCase invokeTest]_block_invoke_2.214 (XCTest:x86_64+0x2dc6d)
    #12 0x10618113a in -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] (XCTest:x86_64+0xba13a)
    #13 0x1060ff8da in -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] (XCTest:x86_64+0x388da)
    #14 0x1060f4bfd in __24-[XCTestCase invokeTest]_block_invoke.208 (XCTest:x86_64+0x2dbfd)
    #15 0x10616858f in -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] (XCTest:x86_64+0xa158f)
    #16 0x1061684ac in -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] (XCTest:x86_64+0xa14ac)
    #17 0x1060f46ae in __24-[XCTestCase invokeTest]_block_invoke (XCTest:x86_64+0x2d6ae)
    #18 0x1060f41a7 in -[XCTestCase testContextPerformInScope:] (XCTest:x86_64+0x2d1a7)
    #19 0x1060f4241 in -[XCTestCase invokeTest] (XCTest:x86_64+0x2d241)
    #20 0x1060f6020 in __26-[XCTestCase performTest:]_block_invoke_2 (XCTest:x86_64+0x2f020)
    #21 0x10616858f in -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] (XCTest:x86_64+0xa158f)
    #22 0x1061684ac in -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] (XCTest:x86_64+0xa14ac)
    #23 0x1060f5f37 in __26-[XCTestCase performTest:]_block_invoke.342 (XCTest:x86_64+0x2ef37)
    #24 0x10617880b in +[XCTContext runInContextForTestCase:block:] (XCTest:x86_64+0xb180b)
    #25 0x1060f56aa in -[XCTestCase performTest:] (XCTest:x86_64+0x2e6aa)
    #26 0x106147163 in -[XCTest runTest] (XCTest:x86_64+0x80163)
    #27 0x1060efd4a in __27-[XCTestSuite performTest:]_block_invoke (XCTest:x86_64+0x28d4a)
    #28 0x1060ef474 in -[XCTestSuite _performProtectedSectionForTest:testSection:] (XCTest:x86_64+0x28474)
    #29 0x1060ef771 in -[XCTestSuite performTest:] (XCTest:x86_64+0x28771)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x175ed) in wrap_strlen
Shadow bytes around the buggy address:
  0x1c2a000026c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c2a000026d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c2a000026e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c2a000026f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c2a00002700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1c2a00002710:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c2a00002720: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c2a00002730: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c2a00002740: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c2a00002750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c2a00002760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==41340==ABORTING
```

**To Reproduce**
1. run tests with `swift test --sanitize=address --disable-index-store`

**Expected behavior**
passes

 - OS: macOS Catalina

[log_swift_2OMC7b.log](https://github.com/kylebrowning/APNSwift/files/3417487/log_swift_2OMC7b.log)

### PR DESCRIPTION
**Pull request by kylebrowning**
Fixes #31 

@weissi

### CODE REVIEW

File: Sources/APNSwift/APNSwiftSigner.swift [hunk 1]
```diff
@@ -36,7 +36,7 @@ public struct APNSwiftSigner {
         let bio = BIO_new(BIO_s_mem())
         defer { BIO_free(bio) }
         let res = buffer.withUnsafeReadableBytes { ptr in
-            Int(BIO_puts(bio, ptr.baseAddress?.assumingMemoryBound(to: Int8.self)))
+            Int(BIO_write(bio, ptr.baseAddress?.assumingMemoryBound(to: Int8.self), Int32(ptr.count)))
```
Comment (weissi) [inline Sources/APNSwift/APNSwiftSigner.swift]: the memory here isn't bound to `Int8` so that's incorrect. You should use `withMemoryRebound(to: Int8.self)`

File: Sources/APNSwift/APNSwiftSigner.swift [hunk 2]
```diff
@@ -57,10 +57,7 @@ public struct APNSwiftSigner {
         }
 
         var derBytes = ByteBufferAllocator().buffer(capacity: Int(derLength))
```
Comment (weissi) [inline Sources/APNSwift/APNSwiftSigner.swift]: you should use the allocator from the `digest` here instead of creating a new one

Comment (kylebrowning) [reply Sources/APNSwift/APNSwiftSigner.swift]: @weissi `allocator` is private on `ByteBuffer`

Comment (kylebrowning) [reply Sources/APNSwift/APNSwiftSigner.swift]: `private let allocator: ByteBufferAllocator`

Comment (weissi) [reply Sources/APNSwift/APNSwiftSigner.swift]: @kylebrowning ah fair, leave it then :)

File: Sources/APNSwift/APNSwiftSigner.swift (hunk 1 above)
Comment (kylebrowning) [reply Sources/APNSwift/APNSwiftSigner.swift]: `withMemoryRebound` isn't on `UnsafeRawBufferPointer`

What about this, `Int(BIO_write(bio, ptr.baseAddress?.bindMemory(to: Int8.self, capacity: ptr.count), Int32(ptr.count)))`

**Comment by kylebrowning** [comment]
@weissi Okay, take a look when you find a sec. Will push a release with this and the new tests once reviewed.

File: Sources/APNSwift/APNSwiftErrors.swift [hunk 3]
```diff
@@ -60,6 +60,7 @@ public struct APNSwiftError {
         }
     }
     public enum SigningError: Error {
+        case invalidMemoryAssignment
```
Comment (weissi) [inline Sources/APNSwift/APNSwiftErrors.swift]: - extending an `enum` breaks the public API so I'd suggest solving this differently.
- lacks documentation
- also: what is 'invalid memory assignment'?

**Comment by weissi** [comment]
CC @lukasa

File: Sources/APNSwift/APNSwiftErrors.swift (hunk 3 above)
Comment (kylebrowning) [reply Sources/APNSwift/APNSwiftErrors.swift]: It's what happens here, https://github.com/kylebrowning/APNSwift/pull/32/files#diff-8be8c6f83f5ffc88230cf3cf2abd28b3R43

Basically the result is optional, so its a guard to make sure we can assert. I could remove if it there was a way to assert on an optional?

Comment (weissi) [reply Sources/APNSwift/APNSwiftErrors.swift]: if we expect OpenSSL to always set the pointer there, then `!` is the right answer.

Comment (kylebrowning) [reply Sources/APNSwift/APNSwiftErrors.swift]: Okay. We do!

File: Sources/APNSwift/APNSwiftSigner.swift [hunk 4]
```diff
@@ -36,9 +36,14 @@ public struct APNSwiftSigner {
         let bio = BIO_new(BIO_s_mem())
         defer { BIO_free(bio) }
         let res = buffer.withUnsafeReadableBytes { ptr in
-            Int(BIO_puts(bio, ptr.baseAddress?.assumingMemoryBound(to: Int8.self)))
+            ptr.baseAddress?.assumingMemoryBound(to: Int8.self).withMemoryRebound(to: Int8.self, capacity: ptr.count, { newBoundPtr  in
```
Comment (Lukasa) [inline Sources/APNSwift/APNSwiftSigner.swift]: There should be no need to assume the memory bound to a type and then rebind to that same type. 

In this case I think the actual correct thing to do is to bind the memory to the type you want, as you are holding a raw pointer and there’s is no chance of an aliasing issue here.

Comment (weissi) [reply Sources/APNSwift/APNSwiftSigner.swift]: @lukasa ByteBuffer binds it to UInt8 so it’s safe to assume that it’s bound to that. Because we temporarily want to have it as an Int8 (should be CChar) the best I could come up with is to assume it bound to UInt8 and then withMemRebound to temporarily rebind it to Int8

Comment (kylebrowning) [reply Sources/APNSwift/APNSwiftSigner.swift]: Yeah I had assumed bindMemory would be better, but not sure which route to go here!
Looking for guidance.

Comment (Lukasa) [reply Sources/APNSwift/APNSwiftSigner.swift]: We can do that if you want, but that is not what this code does! It assumes the pointer is bound to `Int8`.

Comment (weissi) [reply Sources/APNSwift/APNSwiftSigner.swift]: @lukasa good catch. The code is wrong. I was suggesting `assumingMemBound(to: UInt8.self).withMemoryRebound(to: Int8.self)`

Comment (weissi) [reply Sources/APNSwift/APNSwiftSigner.swift]: I talked to Andy Trick a while ago about this issue. The `assuming(UInt8).withMemRebound(Int8)` is correct for the _ByteBuffer use-case_ if we assume no user ever rebinds which is awkward of course. The only guaranteed to be correct solution is to create a `static inline` wrapper in C which accepts a `const void *` and casts that to the `const char *`. That's exactly what we do in [`CNIOHTTP1`](https://github.com/apple/swift-nio/blob/master/Sources/CNIOHTTPParser/include/CNIOHTTPParser.h#L22-L27)

Comment (kylebrowning) [reply Sources/APNSwift/APNSwiftSigner.swift]: Okay the above should be fixed.

File: Sources/APNSwift/APNSwiftSigner.swift [hunk 5]
```diff
@@ -36,9 +36,11 @@ public struct APNSwiftSigner {
         let bio = BIO_new(BIO_s_mem())
         defer { BIO_free(bio) }
         let res = buffer.withUnsafeReadableBytes { ptr in
-            Int(BIO_puts(bio, ptr.baseAddress?.assumingMemoryBound(to: Int8.self)))
+            ptr.baseAddress?.assumingMemoryBound(to: UInt8.self).withMemoryRebound(to: Int8.self, capacity: ptr.count, { newBoundPtr  in
+                Int(BIO_write(bio, newBoundPtr, CInt(ptr.count)))
```
Comment (weissi) [inline Sources/APNSwift/APNSwiftSigner.swift]: just noticed that `BIO_write` isn't actually stupid and has the right type: `BIO_puts(BIO *b,const char *buf)`. So we don't need any binding. yay

Comment (kylebrowning) [reply Sources/APNSwift/APNSwiftSigner.swift]: Nice find. This has been resolved.

**Comment by weissi** [comment]
Ok, I'm happy, now over to @lukasa for OpenSSL scrutiny :)

**Comment by Lukasa** [comment]
LGTM for now.
